CREATE DATABASE `mydb` /*!40100 DEFAULT CHARACTER SET utf8mb3 */ /*!80016 DEFAULT ENCRYPTION='N' */;
CREATE TABLE `corruption_perception` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `Country` varchar(45) DEFAULT NULL,
  `ISO3` varchar(3) DEFAULT NULL,
  `Region` varchar(10) DEFAULT NULL,
  `CPI_score_2020` int DEFAULT NULL,
  `Rank_2020` int DEFAULT NULL,
  `Sources_2020` int DEFAULT NULL,
  `Standard_error_2020` float DEFAULT NULL,
  `CPI_score_2019` int DEFAULT NULL,
  `Rank_2019` int DEFAULT NULL,
  `Sources_2019` int DEFAULT NULL,
  `Standard_error_2019` float DEFAULT NULL,
  `CPI_score_2018` int DEFAULT NULL,
  `Rank_2018` int DEFAULT NULL,
  `Sources_2018` int DEFAULT NULL,
  `Standard_error_2018` float DEFAULT NULL,
  `CPI_score_2017` int DEFAULT NULL,
  `Rank_2017` int DEFAULT NULL,
  `Sources_2017` int DEFAULT NULL,
  `Standard_error_2017` float DEFAULT NULL,
  `CPI_score_2016` int DEFAULT NULL,
  `Rank_2016` int DEFAULT NULL,
  `Sources_2016` int DEFAULT NULL,
  `Standard_error_2016` float DEFAULT NULL,
  `CPI_score_2015` int DEFAULT NULL,
  `Rank_2015` int DEFAULT NULL,
  `Sources_2015` int DEFAULT NULL,
  `Standard_error_2015` float DEFAULT NULL,
  `CPI_score_2014` int DEFAULT NULL,
  `Rank_2014` int DEFAULT NULL,
  `Sources_2014` int DEFAULT NULL,
  `Standard_error_2014` float DEFAULT NULL,
  `CPI_score_2013` int DEFAULT NULL,
  `Sources_2013` int DEFAULT NULL,
  `Standard_error_2013` float DEFAULT NULL,
  `CPI_score_2012` int DEFAULT NULL,
  `Sources_2012` int DEFAULT NULL,
  `Standard_error_2012` float DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `ISO3` (`ISO3`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

CREATE TABLE `country` (
  `CountryCode` varchar(3) NOT NULL,
  `ShortName` varchar(45) DEFAULT NULL,
  `TableName` varchar(45) DEFAULT NULL,
  `LongName` varchar(45) DEFAULT NULL,
  `2-alphaCode` varchar(3) DEFAULT NULL, -- Changed from `2-alphacode`
  `CurrencyUnit` varchar(45) DEFAULT NULL,
  `SpecialNotes` varchar(255) DEFAULT NULL,
  `Region` varchar(45) DEFAULT NULL,
  `IncomeGroup` varchar(45) DEFAULT NULL,
  `WB2Code` varchar(45) DEFAULT NULL, -- Changed from `WB-2code`
  `Nationalaccountsbaseyear` varchar(5) DEFAULT NULL,
  `Nationalaccountsreferenceyear` varchar(5) DEFAULT NULL,
  `SNApricevaluation` varchar(45) DEFAULT NULL,
  `Lendingcategory` varchar(45) DEFAULT NULL,
  `Othergroups` varchar(30) DEFAULT NULL,
  `SystemofNationalAccounts` varchar(45) DEFAULT NULL,
  `Alternativeconversionfactor` varchar(45) DEFAULT NULL,
  `PPPsurveyyear` varchar(5) DEFAULT NULL,
  `BalanceofPaymentsManualinuse` varchar(30) DEFAULT NULL,
  `ExternaldebtReportingstatus` varchar(45) DEFAULT NULL,
  `Systemoftrade` varchar(30) DEFAULT NULL,
  `GovernmentAccountingconcept` varchar(45) DEFAULT NULL,
  `IMFdatadisseminationstandard` varchar(60) DEFAULT NULL,
  `Latestpopulationcensus` varchar(255) DEFAULT NULL,
  `Latesthouseholdsurvey` varchar(255) DEFAULT NULL,
  `SourceofmostrecentIncomeandexpendituredata` varchar(100) DEFAULT NULL,
  `Vitalregistrationcomplete` varchar(4) DEFAULT NULL,
  `Latestagriculturalcensus` varchar(100) DEFAULT NULL,
  `Latestindustrialdata` varchar(5) DEFAULT NULL,
  `Latesttradedata` varchar(5) DEFAULT NULL,
  PRIMARY KEY (`CountryCode`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

CREATE TABLE `countryseries` (
  `countrycodeid` int NOT NULL AUTO_INCREMENT,
  `CountryCode` varchar(3) NOT NULL,
  `SeriesCode` varchar(45) NOT NULL,
  `DESCRIPTION`  TEXT DEFAULT NULL,
  PRIMARY KEY (`countrycodeid`)
) ENGINE=InnoDB AUTO_INCREMENT=8242 DEFAULT CHARSET=utf8mb3;

CREATE TABLE `data` (
  `iddata` int NOT NULL AUTO_INCREMENT,
  `countryname` varchar(45) DEFAULT NULL,
  `countrycode` varchar(3) DEFAULT NULL,
  `indicatorname` varchar(100) DEFAULT NULL,
  `indicatorcode` varchar(45) DEFAULT NULL,
  `1960` varchar(45) DEFAULT NULL,
  `1961` varchar(45) DEFAULT NULL,
  `1962` varchar(45) DEFAULT NULL,
  `1963` varchar(45) DEFAULT NULL,
  `1964` varchar(45) DEFAULT NULL,
  `1965` varchar(45) DEFAULT NULL,
  `1966` varchar(45) DEFAULT NULL,
  `1967` varchar(45) DEFAULT NULL,
  `1968` varchar(45) DEFAULT NULL,
  `1969` varchar(45) DEFAULT NULL,
  `1970` varchar(45) DEFAULT NULL,
  `1971` varchar(45) DEFAULT NULL,
  `1972` varchar(45) DEFAULT NULL,
  `1973` varchar(45) DEFAULT NULL,
  `1974` varchar(45) DEFAULT NULL,
  `1975` varchar(45) DEFAULT NULL,
  `1976` varchar(45) DEFAULT NULL,
  `1978` varchar(45) DEFAULT NULL,
  `1979` varchar(45) DEFAULT NULL,
  `1980` varchar(45) DEFAULT NULL,
  `1981` varchar(45) DEFAULT NULL,
  `1982` varchar(45) DEFAULT NULL,
  `1983` varchar(45) DEFAULT NULL,
  `1984` varchar(45) DEFAULT NULL,
  `1985` varchar(45) DEFAULT NULL,
  `1986` varchar(45) DEFAULT NULL,
  `1987` varchar(45) DEFAULT NULL,
  `1988` varchar(45) DEFAULT NULL,
  `1989` varchar(45) DEFAULT NULL,
  `1990` varchar(45) DEFAULT NULL,
  `1991` varchar(45) DEFAULT NULL,
  `1992` varchar(45) DEFAULT NULL,
  `1993` varchar(45) DEFAULT NULL,
  `1994` varchar(45) DEFAULT NULL,
  `1995` varchar(45) DEFAULT NULL,
  `1996` varchar(45) DEFAULT NULL,
  `1997` varchar(45) DEFAULT NULL,
  `1998` varchar(45) DEFAULT NULL,
  `1999` varchar(45) DEFAULT NULL,
  `2000` varchar(45) DEFAULT NULL,
  `2001` varchar(45) DEFAULT NULL,
  `2002` varchar(45) DEFAULT NULL,
  `2003` varchar(45) DEFAULT NULL,
  `2004` varchar(45) DEFAULT NULL,
  `2005` varchar(45) DEFAULT NULL,
  `2006` varchar(45) DEFAULT NULL,
  `2007` varchar(45) DEFAULT NULL,
  `2008` varchar(45) DEFAULT NULL,
  `2009` varchar(45) DEFAULT NULL,
  `2010` varchar(45) DEFAULT NULL,
  `2011` varchar(45) DEFAULT NULL,
  `2012` varchar(45) DEFAULT NULL,
  `2013` varchar(45) DEFAULT NULL,
  `2014` varchar(45) DEFAULT NULL,
  `2015` varchar(45) DEFAULT NULL,
  `2016` varchar(45) DEFAULT NULL,
  `2017` varchar(45) DEFAULT NULL,
  `2018` varchar(45) DEFAULT NULL,
  `2019` varchar(45) DEFAULT NULL,
  `2020` varchar(45) DEFAULT NULL,
  `2021` varchar(45) DEFAULT NULL,
  `2022` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`iddata`),
  KEY `fk_countrycode_data` (`countrycode`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

CREATE TABLE `series` (
  `SeriesCode` varchar(50) NOT NULL,
  `Topic` varchar(500) DEFAULT NULL,
  `IndicatorName` varchar(500) DEFAULT NULL,
  `Shortdefinition` text,
  `Longdefinition` text,
  `Unitofmeasure` text,
  `Periodicity` varchar(45) DEFAULT NULL,
  `BasePeriod` varchar(50) DEFAULT NULL,
  `Othernotes` text,
  `Aggregationmethod` varchar(100) DEFAULT NULL,
  `Limitationsandexceptions` text,
  `Notesfromoriginalsource` text,
  `Generalcomments` text,
  `Source` text,
  `Statisticalconceptandmethodology` text,
  `Developmentrelevance` text,
  `Relatedsourcelinks` text,
  `Otherweblinks` text,
  `Relatedindicators` varchar(1000) DEFAULT NULL,
  `Licensetype` text,
  PRIMARY KEY (`SeriesCode`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

CREATE TABLE `seriestime` (
  `seriestimeid` int NOT NULL AUTO_INCREMENT,
  `seriescode` varchar(45) NOT NULL,
  `year` varchar(45) DEFAULT NULL,
  `DESCRIPTION` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`seriestimeid`),
  KEY `idx_seriescode_seriestime` (`seriescode`)
) ENGINE=InnoDB AUTO_INCREMENT=150 DEFAULT CHARSET=utf8mb3;

CREATE TABLE `footnote` (
  `footnoteid` int NOT NULL AUTO_INCREMENT,
  `CountryCode` varchar(3) NOT NULL,
  `SeriesCode` varchar(45) DEFAULT NULL,
  `Year` varchar(10) DEFAULT NULL,
  `DESCRIPTION` text,
  PRIMARY KEY (`footnoteid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;






